### ISSUE TITLE
Missing support for a runtime configuration file

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#25]
The runtime needs a configuration file for runtime specific settings:

- Hypervisor
  - hypervisor path
  - Guest kernel path
  - Guest OS image path

- Agent
  - Agent configuration (socket paths)

**Comment by sameo** [comment]
I recommend [toml](https://github.com/toml-lang/toml) for the configuration file format:

```Toml
# Clear Containers runtime configuration file

[hypervisor]
path = "/usr/bin/qemu-lite-system-x86_64"
kernel = "/usr/share/clear-containers/vmlinux.container"
image = "/usr/share/clear-containers/clear-containers.img"

[agent]
type = "hyperstart"

[proxy]
type = "ccProxy"
```

together with https://github.com/BurntSushi/toml, it should make for a simple, easy to read and parse configuration file.

**Comment by sameo** [comment]
@dlespiau @sboeuf @amshinde

**Comment by dlespiau** [comment]
@sameo it may be useful to have a bit more "typing" so we can evolve the config keys without breaking compatibility:

```
[global]
hypervisor = "qemu" | "qemu-lite"
agent = "hyperstart"

[qemu-lite]
path = "/usr/bin/qemu-lite-system-x86_64"
kernel = "/usr/share/clear-containers/vmlinux.container"
image = "/usr/share/clear-containers/clear-containers.img"

[hyperstart]
ctl_path = "/var/run/clear-containers/ctl.sock"
io_path = "/var/run/clear-containers/ctl.sock"
```

For instance we would treat qemu and qemu-lite differently (eg. machine type)

**Comment by sboeuf** [comment]
@sameo Do you mean this file will be located in a well known path from the runtime ?

**Comment by sboeuf** [comment]
@dlespiau yes I agree it would avoid any breakage in case we want to change someday our agent or hypervisor

**Comment by sameo** [comment]
@dlespiau, @sboeuf  would something like that work for you guys:

```Toml
# Clear Containers runtime configuration file

[hypervisor.qemu-lite]
path = "/usr/bin/qemu-lite-system-x86_64"
kernel = "/usr/share/clear-containers/vmlinux.container"
image = "/usr/share/clear-containers/clear-containers.img"

[agent.hyperstart]
ctl_path = "/var/run/clear-containers/ctl.sock"
io_path = "/var/run/clear-containers/ctl.sock"
```
