### ISSUE TITLE
Docker Compose: Attach fails

### ISSUE THREAD

**Issue by mcastelino** [clearcontainers/runtime#816]
# Description of problem

docker-compose up 
with
docker-compose.yml
```
version: '3'
services:
 alpine:
   image: alpine
   networks:
           - network1
           - network2
           - network3

networks:
  network1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "network1"
    ipam:
      driver: default
      config:
        - subnet: 10.1.10.0/24
  network2:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "network2"
    ipam:
      driver: default
      config:
        - subnet: 10.2.10.0/24
  network3:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "network3"
    ipam:
      driver: default
      config:
        - subnet: 10.3.10.0/24
```
with docker-compose 

Results in the container created with all the three networks attached. But docker-compose is unable to attach to the created container. As a result docker-compose hangs.

# Expected result

A sucessfull attach to the container followed by deletion

```
Creating compose_alpine_1 ...
Creating compose_alpine_1 ... done
Attaching to compose_alpine_1
compose_alpine_1 exited with code 0
```

# Actual result

Hung at

```
Creating compose_alpine_1 ...
Creating compose_alpine_1 ... done
Attaching to compose_alpine_1
```

---
```
/usr/bin/cc-runtime --version
cc-runtime  : 3.0.8
   commit   : 9c69a8a
   OCI specs: 1.0.0-dev

Server Version: 17.06.0-ce
Storage Driver: overlay2
```
