### ISSUE TITLE
pod resources are not honoured in pod config file

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#925]
# Description of problem

using constraints, pod vCPus and Memory are always 0 in kubernetes

run a container with kubernetes and take a look to the pod config file

```sh
kubectl --namespace=sandbox create -f ~/debian.yaml
cat /var/lib/virtcontainers/pods/$ID/config.json
... "VMConfig":{"VCPUs":0,"Memory":0}
```
_debian.yaml_

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test1
    image: debian
    resources:
      limits:
        cpu: "4"
    args: [ nproc ]
    tty: true
  - name: test2
    image: debian
    args: [ echo, "bye world!" ]
  - name: test3
    image: debian
    resources:
      limits:
        cpu: "3"
    args:
    - bash
    stdin: true
    tty: true
```

do the same, but using docker

```sh
docker run -dti --cpus=5 debian bash
cat /var/lib/virtcontainers/pods/$ID/config.json
... "VMConfig":{"VCPUs":5,"Memory":0}
```

# Expected result

resources should not be 0 in the pod configuration
